const accessToken =
  "eyJhbGciOiJSUzI1NiIsImtpZCI6ImFhMDhlN2M3ODNkYjhjOGFjNGNhNzJhZjdmOWRkN2JiMzk4ZjE2ZGMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vc3dpbXdpbGQtYzJjYTciLCJhdWQiOiJzd2ltd2lsZC1jMmNhNyIsImF1dGhfdGltZSI6MTY5NTExMzg4OCwidXNlcl9pZCI6IlVIYUtNUXg0TUxickVMbnk3NFVZTXlVQmNPbTIiLCJzdWIiOiJVSGFLTVF4NE1MYnJFTG55NzRVWU15VUJjT20yIiwiaWF0IjoxNjk1MTEzODg4LCJleHAiOjE2OTUxMTc0ODgsImVtYWlsIjoidGVzdEBvdXRsb29rLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJ0ZXN0QG91dGxvb2suY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.n3RVBTJ7LrtVvorzVEtPBRTwXjXllFyMekmQj1UlKDRuaIVPyrGTg6IxmTV4B9ZQOCloXSDAaZmd-FdZm5Pg0p_NhvUTVBR3dhTVi0R5bIIsVvAncZJwAvui9QopDHHtWt8IA9au0qKJ__BufWgtasVJaDKIp24eEB82bSwK0EQVFWSqOBD8nrHAJgT_mWW-rcKuUOySDGIMLw3UoI8a0hfyLU-y49yGHQrnjWSEPOzp9XaE1NRFh1AXYM8qG_KG-gZoKrGLMroUdezjb3Rifa3ohy16Mfw90Vl6XjL1goLJiyPsw2IDO4GlKyATx0EXfScEyCaXUWGHgv5sg_143g";

module.exports = { accessToken, test2atOutlookComToken };

`curl 'https://www.googleapis.com/identitytoolkit/v3/relyingparty/verifyPassword?key=AIzaSyABjPb5ApAILuDCTMwHUPBh78nnCLhZmMg' \
-H 'Content-Type: application/json' \
--data-binary '{"email":"test2@outlook.com","password":"password","returnSecureToken":true}'`;
