module.exports = [
  {
    uid: "QyqF2JQjSEY6TOqDvdaSAd99WyA2",
    name: "Aija Warwick Sorenson",
    nickname: "aijswims92",
    profileImg:
      "https://media.vogue.co.uk/photos/64b9aa1d06ebd79a7be60edb/2:3/w_2560%2Cc_limit/R3_0008_oppen_5p_timed_ip_r03A_bt1886.0265416.jpg",

    dob: "1993-09-02T11:00:00+0000",
    bio: "Swimming is my passion. I love being cold. Lakes are my favourite as I hate getting salty.",
    home: "Rydal, Ambleside LA22 9SD",
    swims: [
      {
        date: "2023-09-02T11:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes:
          "A great swim! To the dog's grave on the main island and back. Water not too cold.",
        stars: 5,
        recordTemp: null,
        feelTemp: "average",
        mins: 45,
        km: 1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "muddy",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://upload.wikimedia.org/wikipedia/commons/b/b4/Cumbria_2007_035.jpg",
        ],
      },
      {
        date: "2023-05-07T17:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes: "Pretty cold! Would recommend a wet suit...",
        stars: 4,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 5,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://files.holidaycottages.co.uk/docs/lakelandcottagecompany/RW1resize.jpg",
        ],
      },
      {
        date: "2023-08-29T18:00:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Extremely cold, wetsuit necessary. Clear water though, but lots of seaweed and still quite shallow a long way out.",
        stars: 3,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 20,
        km: 0.5,
        outOfDepth: false,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://assets.bedful.com/images/c36604cce170b0e7b1e6504ac794699d3e538b47/small.jpg",
        ],
      },
    ],
  },
  {
    uid: "UHaKMQx4MLbrELny74UYMyUBcOm2",
    name: "Pete Jacobs",
    nickname: "frontcrawl31",
    profileImg:
      "https://images.unsplash.com/photo-1503110906525-c5254a531c64?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWFuJTIwc3dpbW1pbmd8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    dob: "1997-09-02T11:00:00+0000",
    bio: "My life is swimming. All the strokes, not just front crawl. Swimming and sleeping.",
    home: "Burleigh Rd, Hinckley LE10 0DG",
    swims: [
      {
        date: "2023-06-21T17:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes: "Good fun",
        stars: 4,
        recordTemp: null,
        feelTemp: "average",
        mins: 25,
        km: 0.5,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://www.parkcliffe.co.uk/wp-content/uploads/2023/01/rydal-water-2-lake-district.jpg",
          "https://www.ratedtrips.com/images/styles/rt_slider/public/00008881_A3.jpg?itok=3BSnVDBP",
          "https://windows10spotlight.com/wp-content/uploads/2022/06/5cc14463fca6e0211691ddf32779fbf2.jpg",
        ],
      },
    ],
  },
  {
    uid: "Ij0FSgFiH0bCL9fQ0TPbBw0slPk2",
    name: "Bodgan Ru Wiśniewski",
    nickname: "bodgancornetto",
    profileImg:
      "https://img.freepik.com/free-photo/side-profile-camel-with-rope-its-mouth-desert-landscape_181624-29653.jpg?w=2000",

    dob: "1992-09-02T11:00:00+0000",
    swims: [],
  },
  {
    uid: "voEGvEJ9LeX3bEZvtV9UzXnh66c2",
    name: "Irene Aalto",
    nickname: "irenediving",
    profileImg:
      "https://upload.wikimedia.org/wikipedia/commons/8/8b/Judi_Dench_at_the_BAFTAs_2007_%28cropped%29.jpg",
    dob: "1939-08-02T11:00:00+0000",
    bio: "I've been diving for over 60 years. Still got it!",
    home: "London W5 1LX",
    swims: [
      {
        date: "2023-07-29T18:00:00+0000",
        location: {
          name: "Goldiggins Quarry, Minions, Cornwall",
          id: null,
        },
      },
    ],
  },
  {
    uid: "pj21fy7d1FYBxCO2zaf48e9bxBE3",
    name: "Adi Kate",
    nickname: "adirules33",
    profileImg:
      "https://i0.wp.com/www.devon-cornwall-film.co.uk/wp-content/uploads/2019/07/jennifer-anniston-shutterstock_1072912976.jpg?fit=500%2C458&ssl=1",
    dob: "1983-02-05T19:00:00+0000",
    home: "Grantham NG31 9JY",
    bio: "Just thought this looked like fun. Other than swimming I like chess, rowing, and playing with lego.",
    swims: [
      {
        date: "2023-09-21T11:00:00+0000",
        location: {
          name: "Linhope Spout, Northumberland",
          id: null,
        },
        notes:
          "Lovely bracing swim. Water was a bit peaty though but probably just due to last night's rain fall.",
        stars: 4,
        recordTemp: null,
        feelTemp: "cold",
        mins: 8,
        km: null,
        outOfDepth: false,
        sizeKey: "tiny",
        shore: "rocky",
        bankAngle: "steep",
        clarity: "average",
        imgUrls: [
          "https://www.google.com/search?sca_esv=567587230&sxsrf=AM9HkKm0F9r_Ixqaz96SNt9aN67aHu7ejg:1695387983576&q=linhope+spout&tbm=isch&source=lnms&sa=X&sqi=2&ved=2ahUKEwi-1Y-0pL6BAxWCZsAKHc-gA6wQ0pQJegQICBAB&biw=939&bih=740&dpr=2#imgrc=JWTmIDuKkstrBM",
        ],
      },
    ],
  },
  {
    uid: "QRI8lUM1URYy2vCN3tSHSkU560S2",
    name: "Briana Lenore Sebastiani",
    nickname: "brianaswims",
    profileImg:
      "https://img.olympicchannel.com/images/image/private/t_s_pog_staticContent_hero_lg_2x/f_auto/v1668613537/primary/z0l02peeuizeeg8oqq6x",
    dob: "1996-04-24T07:30:00+0000",
    home: "Falmouth, UK",
    bio: "Swimming, surfing, bbq, kangeroos. That's my scene.",
    swims: [
      {
        date: "2023-01-01T08:30:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Great swim on New Year's Day with the family! Sea was rough but it was a right laugh. Even saw a seal!",
        stars: 5,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 5,
        km: null,
        outOfDepth: false,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://lh3.googleusercontent.com/p/AF1QipPTjU2zKsuu9CJ_C2KmtPl37RM-xYTufMDBMPaS=s1360-w1360-h1020",
        ],
      },
      {
        date: "2022-08-05T07:00:00+0000",
        location: {
          name: "Burnsall, River Wharfe",
          id: null,
        },
        notes:
          "Would recommend going early if it's a sunny day in the school summer holidays",
        stars: 5,
        recordTemp: null,
        feelTemp: "warm",
        mins: 10,
        km: null,
        outOfDepth: false,
        sizeKey: "small",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://files.holidaycottages.co.uk/gorgeouscottages%2Fguides%2F1689166492104-Kisdon+Force.jpg",
        ],
      },
    ],
  },
  {
    uid: "g1JGTlWQKka03Kza0bVyQIXR25u1",
    name: "Greg Seymour",
    nickname: "gregthemeg",
    profileImg:
      "https://media.istockphoto.com/id/1125707375/photo/businessman-going-to-office-on-bicycle.jpg?s=612x612&w=0&k=20&c=gnUglrbu8j0g7oDNsmSKMzoY1_Ho7sGZ0xSboVXkS_8=",
    dob: "1990-07-05T19:00:00+0000",
    home: "Bolton, UK",
    bio: "Came here to make some new friends. Let's go swimming together. Please :)",
    swims: [
      {
        date: "2023-08-22T15:00:00+0000",
        location: {
          name: "River Isis, Port Meadow, Oxford",
          id: null,
        },
        notes: "Favourite swimming spot in Oxford",
        stars: 5,
        recordTemp: 15,
        feelTemp: "freezing",
        mins: 15,
        km: 0.5,
        outOfDepth: false,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVBkVZUMJRc4rwZzIuVlhO2iVvvMt4IpgjNA&usqp=CAU",
        ],
      },
      {
        date: "2023-02-24T13:45:00+0000",
        location: {
          name: "National Trust - Fell Foot, Windermere",
          id: null,
        },
        notes:
          "Me and the wife have been staying in the area on holiday and are keen wild swimmers but hadn't been here yet. We were on our way up to Bowness but had to have a quick post-lunch swim on our drive past. Weather was a bit grey and miserable but the swim was great. Had a coffee after to warm up and a slice of cake too in the cafe. 5/5",
        stars: 5,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 7,
        km: null,
        outOfDepth: false,
        sizeKey: "large",
        shore: "rocky",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://www.sykescottages.co.uk/inspiration/wp-content/uploads/Fell-Foot-Park-Windermere.jpg",
        ],
      },
      {
        date: "2023-08-14T11:00:00+0000",
        location: {
          name: "Burnsall, River Wharfe",
          id: null,
        },
        notes:
          "Was told to come here by some friends but afraid I can't recommend - water was cold and fast flowing, also no easy access into the river",
        stars: 2,
        recordTemp: null,
        feelTemp: "cold",
        mins: null,
        km: null,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "rocky",
        bankAngle: "medium",
        clarity: "murky",
        imgUrls: ["https://www.yorkshire-dales.com/appletreewick-05.jpg"],
      },
      {
        date: "2023-06-24T15:00:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Weather was overcast meaning air temp felt a little cold so only had a quick dip. Would have put my swim gloves and socks on but forgot them! If the tide is out it's a long walk down to the sea",
        stars: 4,
        recordTemp: null,
        feelTemp: "cold",
        mins: 5,
        km: null,
        outOfDepth: false,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://files.holidaycottages.co.uk/docs/cottagesinnorthumberland/warkworthresize.jpg",
        ],
      },
    ],
  },
  {
    uid: "EwbJgpliD7cixTGHecaaXknO0xj1",
    name: "Kendall Anastasiya Fromm",
    nickname: "kendallcalling",
    profileImg:
      "https://media.istockphoto.com/id/1253485108/photo/hiking-selfie.jpg?s=612x612&w=0&k=20&c=R0PJYtqiKwQc8Ck1hK8WEn1eFN3-7hypNcJfcb1Jx3U=",
    dob: "1972-02-04T12:00:00+0000",
    home: "Hexham, Northumberland",
    bio: "My hobbies include walking, hiking, wild swimming, white-water rafting, climbing, white water skiing, wild hiking, rock walking, water ski-rafting, wild white-water hiking, tennis",
    swims: [
      {
        date: "2023-09-01T15:00:00+0000",
        location: {
          name: "River Isis, Port Meadow, Oxford",
          id: null,
        },
        notes: "Disgusting. Water was swampy and stank",
        stars: 2,
        recordTemp: null,
        feelTemp: "average",
        mins: null,
        km: null,
        outOfDepth: false,
        sizeKey: "medium",
        shore: "swampy",
        bankAngle: "steep",
        clarity: "muddy",
        imgUrls: [
          "https://static.independent.co.uk/2022/04/12/08/newFile-2.jpg?width=1200",
        ],
      },
      {
        date: "2022-03-10T10:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes:
          "Came with my swimming group for the first time. Great spot for swimming but water wasn't the clearest because of recent rainfall. Needed the wetsuit on and a cuppa afterwards!",
        stars: 4,
        recordTemp: null,
        feelTemp: "cold",
        mins: 35,
        km: 1,
        outOfDepth: false,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.swimthelakes.co.uk%2F11095%2Flake-swimming%2Flake-swimming-rydal-water%2F&psig=AOvVaw3VjKR0J5knQ4UZ4Jt--ij4&ust=1695478471099000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCMDIkNKzvoEDFQAAAAAdAAAAABAJ",
        ],
      },
      {
        date: "2021-05-29T17:30:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Water always a bit murky here but a great swim on a hot day after work! Sea was a little choppy but still felt safe",
        stars: 5,
        recordTemp: 16,
        feelTemp: "warm",
        mins: 10,
        km: 0.1,
        outOfDepth: false,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://media-cdn.tripadvisor.com/media/photo-s/07/e5/b2/ce/warkworth-beach.jpg",
        ],
      },
    ],
  },
  {
    uid: "ydfx9juG2cZvRMkxBtfrrIzylwI3",
    name: "Nikolaus Nuan Hyland",
    nickname: "trickynicky",
    profileImg:
      "https://i.ytimg.com/vi/DGz5dyfwpg0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD-wS1lLsig88D6jIYp0bOWas5AUg",
    dob: "1974-09-24T15:00:00+0000",
    home: "Birmingham, UK",
    bio: "Just love getting outdoors and seeing the world! Follow my adventures on YouTube.",
    swims: [
      {
        date: "2023-05-15T11:30:00+0000",
        location: {
          name: "Sandsend Beach, Whitby",
          id: null,
        },
        notes:
          "Litter everywhere and sea was choppy. Still enjoyed the swim but probably won't come back again",
        stars: 3,
        recordTemp: 13,
        feelTemp: "cold",
        mins: 17,
        km: 0.3,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/3f/6f/f7/sandsend-beach.jpg?w=2000&h=-1&s=1",
        ],
      },
      {
        date: "2022-08-02T15:00:00+0000",
        location: {
          name: "National Trust - Fell Foot, Windermere",
          id: null,
        },
        notes:
          "Came to go paddle boarding but the weather ending up being so nice we had to have a dip too. Hired some kayaks for the kids whilst we swam alongside. There are some steps to help you get in but a bit rocky underfoot so would recommend wearing swim shoes. Was a bit busy but it's the school summer holidays so to be expected. Cafe is nice too but a bit pricey.",
        stars: 4,
        recordTemp: null,
        feelTemp: "warm",
        mins: 15,
        km: 1,
        outOfDepth: false,
        sizeKey: "large",
        shore: "rocky",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/c0/b7/87/fun-at-the-lake.jpg?w=1400&h=-1&s=1",
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/32/ce/c7/caption.jpg?w=1200&h=-1&s=1",
        ],
      },
      {
        date: "2023-02-15T07:30:00+0000",
        location: {
          name: "Durdle Door, Dorset",
          id: null,
        },
        notes:
          "Quick morning dip with my friend Val. Wet and windy so not for the fainthearted, but exhilarating! Bring a flask for after!",
        stars: 5,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 6,
        km: null,
        outOfDepth: false,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/1f/e4/d7/photo3jpg.jpg?w=1400&h=-1&s=1",
        ],
      },
    ],
  },
  {
    uid: "9X5LxxfdfShRImNpRMbYdboyd1i1",
    name: "Aiman, Vladimir Campbell",
    nickname: "Aymannotcool",
    profileImg:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fHww&w=1000&q=80",
    dob: "1999-01-15T22:00:00+0000",
    home: "Shrewsbury, UK",
    bio: "I can swim 2km in under 30 minutes. I am like lightening in the water.",
    swims: [
      {
        date: "2023-03-31T08:00:00+0000",
        location: {
          name: "Sandsend Beach, Whitby",
          id: null,
        },
        notes:
          "Has become my daily swim spot since moving nearby. Really beautiful morning today!",
        stars: 5,
        recordTemp: 10,
        feelTemp: "cold",
        mins: 10,
        km: 0.5,
        outOfDepth: false,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/bd/a8/4e/sandsend-beach.jpg?w=1400&h=-1&s=1",
        ],
      },
      {
        date: "2023-04-05T16:30:00+0000",
        location: {
          name: "National Trust - Fell Foot, Windermere",
          id: null,
        },
        notes:
          "Water seemed a bit murkier than usual but a good swim regardless.",
        stars: 4,
        recordTemp: 10,
        feelTemp: "average",
        mins: 30,
        km: 1,
        outOfDepth: false,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "medium",
        clarity: "murky",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/82/87/0e/20180401-135947-largejpg.jpg?w=800&h=-1&s=1",
        ],
      },
      {
        date: "2023-05-19T14:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes:
          "Gorgeous swim at Rydal Water today! Water was a little bit cold so had to put my swim gloves and hat on",
        stars: 5,
        recordTemp: 12,
        feelTemp: "cold",
        mins: 10,
        km: null,
        outOfDepth: false,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "perfect",
        imgUrls: [
          "https://swimmingthelakes.files.wordpress.com/2015/10/rydal-water-035.jpg",
        ],
      },
    ],
  },
];
