module.exports = [
  {
    uid: "QyqF2JQjSEY6TOqDvdaSAd99WyA2",
    name: "Aija Warwick Sorenson",
    nickname: "aijswims92",
    profileImg:
      "https://media.vogue.co.uk/photos/64b9aa1d06ebd79a7be60edb/2:3/w_2560%2Cc_limit/R3_0008_oppen_5p_timed_ip_r03A_bt1886.0265416.jpg",

    dob: "1993-09-02T11:00:00+0000",
    bio: "Swimming is my passion. I love being cold. Lakes are my favourite as I hate getting salty.",
    home: "Rydal, Ambleside LA22 9SD",
    swims: [
      {
        date: "2023-09-02T11:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes:
          "A great swim! To the dog's grave on the main island and back. Water not too cold.",
        stars: 5,
        recordTemp: null,
        feelTemp: "average",
        mins: 45,
        km: 1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "muddy",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://upload.wikimedia.org/wikipedia/commons/b/b4/Cumbria_2007_035.jpg",
        ],
      },
      {
        date: "2023-05-07T17:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes: "Pretty cold! Would recommend a wet suit...",
        stars: 4,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 5,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://files.holidaycottages.co.uk/docs/lakelandcottagecompany/RW1resize.jpg",
        ],
      },
      {
        date: "2023-08-29T18:00:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Extremely cold, wetsuit necessary. Clear water though, but lots of seaweed and still quite shallow a long way out.",
        stars: 3,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 20,
        km: 0.5,
        outOfDepth: true,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://assets.bedful.com/images/c36604cce170b0e7b1e6504ac794699d3e538b47/small.jpg",
        ],
      },
      {
        date: "2023-02-15T07:30:00+0000",
        location: {
          name: "Durdle Door, Dorset",
          id: null,
        },
        notes:
          "Quick morning dip with my friend Val. Wet and windy so not for the fainthearted, but exhilarating! Bring a flask for after!",
        stars: 5,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 6,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/1f/e4/d7/photo3jpg.jpg?w=1400&h=-1&s=1",
        ],
      },
    ],
  },
  {
    uid: "UHaKMQx4MLbrELny74UYMyUBcOm2",
    name: "Pete Jacobs",
    nickname: "frontcrawl31",
    profileImg:
      "https://images.unsplash.com/photo-1503110906525-c5254a531c64?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8bWFuJTIwc3dpbW1pbmd8ZW58MHx8MHx8fDA%3D&w=1000&q=80",
    dob: "1997-09-02T11:00:00+0000",
    bio: "My life is swimming. All the strokes, not just front crawl. Swimming and sleeping.",
    home: "Burleigh Rd, Hinckley LE10 0DG",
    swims: [
      {
        date: "2023-06-21T17:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes: "Good fun",
        stars: 4,
        recordTemp: null,
        feelTemp: "average",
        mins: 25,
        km: 0.5,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://www.parkcliffe.co.uk/wp-content/uploads/2023/01/rydal-water-2-lake-district.jpg",
          "https://www.ratedtrips.com/images/styles/rt_slider/public/00008881_A3.jpg?itok=3BSnVDBP",
          "https://windows10spotlight.com/wp-content/uploads/2022/06/5cc14463fca6e0211691ddf32779fbf2.jpg",
        ],
      },
      {
        date: "2023-08-04T14:00:00+0000",
        location: {
          name: "Durdle Door, Dorset",
          id: null,
        },
        notes:
          "Beach gets busy and the parking is a pain, but a great spot. Swam a bit too far out so take care",
        stars: 4,
        recordTemp: 18,
        feelTemp: "warm",
        mins: 25,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/36/4b/e3/caption.jpg?w=1100&h=-1&s=1",
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/36/4b/e2/caption.jpg?w=1100&h=-1&s=1",
        ],
      },
      {
        date: "2021-06-19T14:00:00+0000",
        location: {
          name: "Linhope Spout, Northumberland",
          id: null,
        },
        notes:
          "Great dip this morning. It seems to get busy on hot summer days so I'd recommend going early or in the late afternoon. Water is pretty cold but very refreshing. It's not the easiest to access so it's a good idea to wear swim socks or just jump right in",
        stars: 5,
        recordTemp: null,
        feelTemp: "cold",
        mins: 10,
        km: null,
        outOfDepth: false,
        sizeKey: "tiny",
        shore: "rocky",
        bankAngle: "jump-in",
        clarity: "perfect",
        imgUrls: [
          "https://i.ytimg.com/vi/Nc61VeJ8QlI/maxresdefault.jpg",
          "https://i2-prod.chroniclelive.co.uk/incoming/article18317370.ece/ALTERNATES/s1200c/3_HGR_NEC_270520linhopemess-7jpeg.jpg",
        ],
      },
    ],
  },
  {
    uid: "Ij0FSgFiH0bCL9fQ0TPbBw0slPk2",
    name: "Bodgan Ru Wiśniewski",
    nickname: "bodgancornetto",
    profileImg:
      "https://img.freepik.com/free-photo/side-profile-camel-with-rope-its-mouth-desert-landscape_181624-29653.jpg?w=2000",

    dob: "1992-09-02T11:00:00+0000",
    swims: [
      {
        date: "2021-06-19T14:00:00+0000",
        location: {
          name: "Goldiggins Quarry, Minions, Cornwall",
          id: null,
        },
        notes:
          "Have wanted to come here for ages but was a bit disappointed as the access wasn't great. If you like jumping straight in you'll be fine",
        stars: 2,
        recordTemp: 10,
        feelTemp: "cold",
        mins: 5,
        km: null,
        outOfDepth: true,
        sizeKey: "small",
        shore: "rocky",
        bankAngle: "jump-in",
        clarity: "murky",
        imgUrls: [
          "https://thegirloutdoors.co.uk/wp-content/uploads/2019/01/IMG_3254.jpg",
        ],
      },
      {
        date: "2023-06-22T10:30:00+0000",
        location: {
          name: "Goldiggins Quarry, Minions, Cornwall",
          id: null,
        },
        notes:
          "One of our favourite places to swim. Still, clear waters as always",
        stars: 5,
        recordTemp: 13,
        feelTemp: "average",
        mins: 15,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "small",
        shore: "grassy",
        bankAngle: "medium",
        clarity: "perfect",
        imgUrls: [
          "https://www.treworgeycottages.com/images/blog/2022/wild%20swimming/golddiggings%202.jpg",
          "https://files.holidaycottages.co.uk/stayincornwall%2Fguides%2F1610623265833-goldiggins-quarry-resize.jpg",
        ],
      },
      {
        date: "2023-06-22T10:30:00+0000",
        location: {
          name: "Walpole Bay Tidal Pool, Margate",
          id: null,
        },
        notes:
          "Great that you can go for a swim regardless of the tide. Makes it feel really safe. Water was lovely and warm but a little cloudy. The path around can be slippery so take care",
        stars: 5,
        recordTemp: 18,
        feelTemp: "warm",
        mins: 20,
        km: null,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "rocky",
        bankAngle: "steep",
        clarity: "murky",
        imgUrls: [
          "https://www.visitthanet.co.uk/media/29711/walpole-bay-tidal-pool.jpg?quality=75",
        ],
      },
    ],
  },
  {
    uid: "voEGvEJ9LeX3bEZvtV9UzXnh66c2",
    name: "Irene Aalto",
    nickname: "irenediving",
    profileImg:
      "https://upload.wikimedia.org/wikipedia/commons/8/8b/Judi_Dench_at_the_BAFTAs_2007_%28cropped%29.jpg",
    dob: "1939-08-02T11:00:00+0000",
    bio: "I've been diving for over 60 years. Still got it!",
    home: "London W5 1LX",
    swims: [
      {
        date: "2023-07-29T18:00:00+0000",
        location: {
          name: "Goldiggins Quarry, Minions, Cornwall",
          id: null,
        },
        notes: "Great for diving, will definitely be back.",
        stars: 5,
        recordTemp: 19,
        feelTemp: "warm",
        mins: 25,
        km: 0.5,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "grassy",
        bankAngle: "jump-in",
        clarity: "average",
        imgUrls: [
          "https://www.wildthingspublishing.com/wp-content/uploads/2014/08/IMG_0478.jpg",
        ],
      },
      {
        date: "2022-09-05T16:00:00+0000",
        location: {
          name: "Walpole Bay Tidal Pool, Margate",
          id: null,
        },
        notes:
          "Water is murky and shallow so wasn't the best swim, especially when the weather is overcast.",
        stars: 3,
        recordTemp: 17,
        feelTemp: "hot",
        mins: null,
        km: 1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "medium",
        clarity: "murky",
        imgUrls: [
          "https://beachsearcher.com/images/beaches/826201008/UK201008_fit_550_300.jpg",
        ],
      },
      {
        date: "2023-08-25T13:45:00+0000",
        location: {
          name: "Beckenham Park Swimming Lake, London",
          id: null,
        },
        notes:
          "Nice place but busy so wouldn't recommend for a proper swim. Water clarity isn't  great either but to be expected.",
        stars: 4,
        recordTemp: 18,
        feelTemp: "warm",
        mins: 30,
        km: null,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "grassy",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://images.squarespace-cdn.com/content/v1/6058878cac0e160e88993761/1669029971158-8K8GS5QXBJYSZWKFC94F/beckenham-place-park-lewisham-things-to-see-and-do-lake-swimmers-in-lake.jpg",
        ],
      },
    ],
  },
  {
    uid: "pj21fy7d1FYBxCO2zaf48e9bxBE3",
    name: "Adi Kate",
    nickname: "adirules33",
    profileImg:
      "https://i0.wp.com/www.devon-cornwall-film.co.uk/wp-content/uploads/2019/07/jennifer-anniston-shutterstock_1072912976.jpg?fit=500%2C458&ssl=1",
    dob: "1983-02-05T19:00:00+0000",
    home: "Grantham NG31 9JY",
    bio: "Just thought this looked like fun. Other than swimming I like chess, rowing, and playing with lego.",
    swims: [
      {
        date: "2023-09-21T11:00:00+0000",
        location: {
          name: "Linhope Spout, Northumberland",
          id: null,
        },
        notes:
          "Lovely bracing swim. Water was a bit peaty though but probably just due to last night's rain fall.",
        stars: 4,
        recordTemp: null,
        feelTemp: "cold",
        mins: 8,
        km: null,
        outOfDepth: true,
        sizeKey: "tiny",
        shore: "rocky",
        bankAngle: "steep",
        clarity: "average",
        imgUrls: [
          "https://www.google.com/search?sca_esv=567587230&sxsrf=AM9HkKm0F9r_Ixqaz96SNt9aN67aHu7ejg:1695387983576&q=linhope+spout&tbm=isch&source=lnms&sa=X&sqi=2&ved=2ahUKEwi-1Y-0pL6BAxWCZsAKHc-gA6wQ0pQJegQICBAB&biw=939&bih=740&dpr=2#imgrc=JWTmIDuKkstrBM",
        ],
      },
      {
        date: "2023-03-14T10:00:00+0000",
        location: {
          name: "Bude Sea Pool, Cornwall",
          id: null,
        },
        notes:
          "Beautiful tidal pool in Cornwall. Went in early spring so water wasn't the warmest, but  warmer than the sea that's for sure!",
        stars: 5,
        recordTemp: 9,
        feelTemp: "cold",
        mins: 40,
        km: 1,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "rocky",
        bankAngle: "steep",
        clarity: "clear",
        imgUrls: [
          "https://thecornishlife.co.uk/wp-content/uploads/2019/07/bude-sea-pool-summerleaze-1-804x1024.jpg",
          "https://thecornishlife.co.uk/wp-content/uploads/2019/07/bude-sea-pool-summerleaze-2.jpg",
        ],
      },
      {
        date: "2023-07-03T10:15:00+0000",
        location: {
          name: "Beckenham Park Swimming Lake, London",
          id: null,
        },
        notes:
          "Clear water and enough space to get some lengths in. Would recommend to anyone",
        stars: 5,
        recordTemp: 17,
        feelTemp: "warm",
        mins: 30,
        km: 0.75,
        outOfDepth: true,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "shallow",
        clarity: "perfect",
        imgUrls: [
          "https://offloadmedia.feverup.com/secretldn.com/wp-content/uploads/2018/06/18094456/Beckenham-Place-Park-3.jpg",
        ],
      },
    ],
  },
  {
    uid: "QRI8lUM1URYy2vCN3tSHSkU560S2",
    name: "Briana Lenore Sebastiani",
    nickname: "brianaswims",
    profileImg:
      "https://img.olympicchannel.com/images/image/private/t_s_pog_staticContent_hero_lg_2x/f_auto/v1668613537/primary/z0l02peeuizeeg8oqq6x",
    dob: "1996-04-24T07:30:00+0000",
    home: "Falmouth, UK",
    bio: "Swimming, surfing, bbq, kangeroos. That's my scene.",
    swims: [
      {
        date: "2023-01-01T08:30:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Great swim on New Year's Day with the family! Sea was rough but it was a right laugh. Even saw a seal!",
        stars: 5,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 5,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://lh3.googleusercontent.com/p/AF1QipPTjU2zKsuu9CJ_C2KmtPl37RM-xYTufMDBMPaS=s1360-w1360-h1020",
        ],
      },
      {
        date: "2022-08-05T07:00:00+0000",
        location: {
          name: "Burnsall, River Wharfe",
          id: null,
        },
        notes:
          "Would recommend going early if it's a sunny day in the school summer holidays",
        stars: 5,
        recordTemp: null,
        feelTemp: "warm",
        mins: 10,
        km: null,
        outOfDepth: true,
        sizeKey: "small",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://files.holidaycottages.co.uk/gorgeouscottages%2Fguides%2F1689166492104-Kisdon+Force.jpg",
        ],
      },
    ],
  },
  {
    uid: "g1JGTlWQKka03Kza0bVyQIXR25u1",
    name: "Greg Seymour",
    nickname: "gregthemeg",
    profileImg:
      "https://media.istockphoto.com/id/1125707375/photo/businessman-going-to-office-on-bicycle.jpg?s=612x612&w=0&k=20&c=gnUglrbu8j0g7oDNsmSKMzoY1_Ho7sGZ0xSboVXkS_8=",
    dob: "1990-07-05T19:00:00+0000",
    home: "Bolton, UK",
    bio: "Came here to make some new friends. Let's go swimming together. Please :)",
    swims: [
      {
        date: "2023-08-22T15:00:00+0000",
        location: {
          name: "River Isis, Port Meadow, Oxford",
          id: null,
        },
        notes: "Favourite swimming spot in Oxford",
        stars: 5,
        recordTemp: 15,
        feelTemp: "freezing",
        mins: 15,
        km: 0.5,
        outOfDepth: false,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVBkVZUMJRc4rwZzIuVlhO2iVvvMt4IpgjNA&usqp=CAU",
        ],
      },
      {
        date: "2023-02-24T13:45:00+0000",
        location: {
          name: "National Trust - Fell Foot, Windermere",
          id: null,
        },
        notes:
          "Me and the wife have been staying in the area on holiday and are keen wild swimmers but hadn't been here yet. We were on our way up to Bowness but had to have a quick post-lunch swim on our drive past. Weather was a bit grey and miserable but the swim was great. Had a coffee after to warm up and a slice of cake too in the cafe. 5/5",
        stars: 5,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 7,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "rocky",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://www.sykescottages.co.uk/inspiration/wp-content/uploads/Fell-Foot-Park-Windermere.jpg",
        ],
      },
      {
        date: "2023-08-14T11:00:00+0000",
        location: {
          name: "Burnsall, River Wharfe",
          id: null,
        },
        notes:
          "Was told to come here by some friends but afraid I can't recommend - water was cold and fast flowing, also no easy access into the river",
        stars: 2,
        recordTemp: null,
        feelTemp: "cold",
        mins: null,
        km: null,
        outOfDepth: false,
        sizeKey: "medium",
        shore: "rocky",
        bankAngle: "medium",
        clarity: "murky",
        imgUrls: ["https://www.yorkshire-dales.com/appletreewick-05.jpg"],
      },
      {
        date: "2023-06-24T15:00:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Weather was overcast meaning air temp felt a little cold so only had a quick dip. Would have put my swim gloves and socks on but forgot them! If the tide is out it's a long walk down to the sea",
        stars: 4,
        recordTemp: null,
        feelTemp: "cold",
        mins: 5,
        km: null,
        outOfDepth: false,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://files.holidaycottages.co.uk/docs/cottagesinnorthumberland/warkworthresize.jpg",
        ],
      },
    ],
  },
  {
    uid: "EwbJgpliD7cixTGHecaaXknO0xj1",
    name: "Kendall Anastasiya Fromm",
    nickname: "kendallcalling",
    profileImg:
      "https://media.istockphoto.com/id/1253485108/photo/hiking-selfie.jpg?s=612x612&w=0&k=20&c=R0PJYtqiKwQc8Ck1hK8WEn1eFN3-7hypNcJfcb1Jx3U=",
    dob: "1972-02-04T12:00:00+0000",
    home: "Hexham, Northumberland",
    bio: "My hobbies include walking, hiking, wild swimming, white-water rafting, climbing, white water skiing, wild hiking, rock walking, water ski-rafting, wild white-water hiking, tennis",
    swims: [
      {
        date: "2023-09-01T15:00:00+0000",
        location: {
          name: "River Isis, Port Meadow, Oxford",
          id: null,
        },
        notes: "Disgusting. Water was swampy and stank",
        stars: 2,
        recordTemp: null,
        feelTemp: "average",
        mins: null,
        km: null,
        outOfDepth: false,
        sizeKey: "medium",
        shore: "swampy",
        bankAngle: "steep",
        clarity: "muddy",
        imgUrls: [
          "https://static.independent.co.uk/2022/04/12/08/newFile-2.jpg?width=1200",
        ],
      },
      {
        date: "2022-03-10T10:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes:
          "Came with my swimming group for the first time. Great spot for swimming but water wasn't the clearest because of recent rainfall. Needed the wetsuit on and a cuppa afterwards!",
        stars: 4,
        recordTemp: null,
        feelTemp: "cold",
        mins: 35,
        km: 1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.swimthelakes.co.uk%2F11095%2Flake-swimming%2Flake-swimming-rydal-water%2F&psig=AOvVaw3VjKR0J5knQ4UZ4Jt--ij4&ust=1695478471099000&source=images&cd=vfe&opi=89978449&ved=0CA8QjRxqFwoTCMDIkNKzvoEDFQAAAAAdAAAAABAJ",
        ],
      },
      {
        date: "2021-05-29T17:30:00+0000",
        location: {
          name: "Warkworth Beach, Northumberland",
          id: null,
        },
        notes:
          "Water always a bit murky here but a great swim on a hot day after work! Sea was a little choppy but still felt safe",
        stars: 5,
        recordTemp: 16,
        feelTemp: "warm",
        mins: 10,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://media-cdn.tripadvisor.com/media/photo-s/07/e5/b2/ce/warkworth-beach.jpg",
        ],
      },
    ],
  },
  {
    uid: "xN7sjcP9JKVsvJcCLwSAhUrwRUE2",
    name: "Nikolaus Nuan Hyland",
    nickname: "trickynicky",
    profileImg:
      "https://i.ytimg.com/vi/DGz5dyfwpg0/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLD-wS1lLsig88D6jIYp0bOWas5AUg",
    dob: "1974-09-24T15:00:00+0000",
    home: "Birmingham, UK",
    bio: "Just love getting outdoors and seeing the world! Follow my adventures on YouTube.",
    swims: [
      {
        date: "2023-07-29T16:46:00+0000",
        location: {
          name: "Grantchester Meadows, Cambridge",
          id: null,
        },
        notes: "A few pond weeds but nice spot for a dip",
        stars: 4,
        recordTemp: 16,
        feelTemp: "warm",
        mins: 15,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "grassy",
        bankAngle: "jump-in",
        clarity: "murky",
        imgUrls: [
          "https://upload.wikimedia.org/wikipedia/commons/d/d9/Banks_of_the_Cam_at_Grantchester.jpg",
          "https://walkiees.s3.amazonaws.com/walks/G/grantchester-meadows/_uncroppedRetina/IMG_20210529_114938.jpg",
        ],
      },
      {
        date: "2022-06-17T15:56:00+0000",
        location: {
          name: "Barcombe Mills - River Ouse, East Sussex",
          id: null,
        },
        notes:
          "Water looks a bit swampy and it's a bit of a scramble to get in, but a nice calm river for a swim.",
        stars: 4,
        recordTemp: 15,
        feelTemp: "average",
        mins: 20,
        km: 0.4,
        outOfDepth: true,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "steep",
        clarity: "murky",
        imgUrls: [
          "https://otsopenwater.files.wordpress.com/2012/07/p1020696.jpg",
          "https://otsopenwater.files.wordpress.com/2012/07/p1020698.jpg",
        ],
      },
      {
        date: "2022-06-17T15:56:00+0000",
        location: {
          name: "Barcombe Mills - River Ouse, East Sussex",
          id: null,
        },
        notes:
          "Glorious place for a swim! Lovely warm water, soft grassy banks, beautiful lush green area - what's not to love! Take care getting in and out of the water as the bank is quite steep.",
        stars: 5,
        recordTemp: 17,
        feelTemp: "warm",
        mins: 35,
        km: 1,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "grassy",
        bankAngle: "steep",
        clarity: "average",
        imgUrls: [
          "https://www.wildswimming.co.uk/wp-content/uploads/place/IMG_4270.jpg",
          "https://www.wildswimming.co.uk/wp-content/uploads/2015/07/Barcombe-by-daniel-Start.jpg",
        ],
      },
      {
        date: "2022-06-17T15:56:00+0000",
        location: {
          name: "St Nectan's Kieve, Cornwall",
          id: null,
        },
        notes:
          "More of a plunge pool than a swim but worth a visit if you're nearby! Cold, refreshing water in a truly magical setting.",
        stars: 5,
        recordTemp: 11,
        feelTemp: "cold",
        mins: 5,
        km: null,
        outOfDepth: false,
        sizeKey: "tiny",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://upload.wikimedia.org/wikipedia/commons/3/3c/St_Nectan%27s_Glen_-_geograph.org.uk_-_596320.jpg",
          "https://kizandsooze.files.wordpress.com/2013/06/waterfall_kiz_220613.jpg",
        ],
      },
      {
        date: "2023-02-07T11:09:00+0000",
        location: {
          name: "River Waveney, Suffolk",
          id: null,
        },
        notes:
          "Lovely swim in the winter sun but not for the faint hearted... Wear your thickest wetsuit - and your hat!",
        stars: 4,
        recordTemp: 5,
        feelTemp: "freezing",
        mins: 5,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "steep",
        clarity: "average",
        imgUrls: [
          "https://www.becclesandbungayjournal.co.uk/resources/images/16974781.png?type=mds-article-620",
        ],
      },
      {
        date: "2023-07-14T17:04:00+0000",
        location: {
          name: "River Waveney, Suffolk",
          id: null,
        },
        notes:
          "A deep stretch of water ideal for swimming, but quite difficult to get out as the bank is steep.",
        stars: 5,
        recordTemp: 16,
        feelTemp: "warm",
        mins: 37,
        km: 0.5,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "grassy",
        bankAngle: "steep",
        clarity: "average",
        imgUrls: [
          "http://www.diggersworld.net/wp-content/uploads/RS19-Bungay-IMG_3882.jpg",
          "http://www.diggersworld.net/wp-content/uploads/RS19-Bungay-P8240015.jpg",
        ],
      },
      {
        date: "2023-05-10T13:04:00+0000",
        location: {
          name: "River Lugg, Herefordshire",
          id: null,
        },
        notes:
          "Shallow at parts but gets deeper depending the further downstream you swim. There are some access points down to the river to make it easier getting in and out, and grassy banks to sit and dry off on.",
        stars: 4,
        recordTemp: 13,
        feelTemp: "average",
        mins: 17,
        km: 0.2,
        outOfDepth: true,
        sizeKey: "small",
        shore: "grassy",
        bankAngle: "medium",
        clarity: "murky",
        imgUrls: [
          "https://ripetomato2uk.files.wordpress.com/2015/06/img_20150627_112631913_hdr.jpg",
          "https://ripetomato2uk.files.wordpress.com/2015/06/img_20150627_112857422_hdr.jpg",
        ],
      },
      {
        date: "2023-05-15T11:30:00+0000",
        location: {
          name: "Sandsend Beach, Whitby",
          id: null,
        },
        notes:
          "Litter everywhere and sea was choppy. Still enjoyed the swim but probably won't come back again",
        stars: 3,
        recordTemp: 13,
        feelTemp: "cold",
        mins: 17,
        km: 0.3,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/3f/6f/f7/sandsend-beach.jpg?w=2000&h=-1&s=1",
        ],
      },
      {
        date: "2022-08-02T15:00:00+0000",
        location: {
          name: "National Trust - Fell Foot, Windermere",
          id: null,
        },
        notes:
          "Came to go paddle boarding but the weather ending up being so nice we had to have a dip too. Hired some kayaks for the kids whilst we swam alongside. There are some steps to help you get in but a bit rocky underfoot so would recommend wearing swim shoes. Was a bit busy but it's the school summer holidays so to be expected. Cafe is nice too but a bit pricey.",
        stars: 4,
        recordTemp: null,
        feelTemp: "warm",
        mins: 15,
        km: 1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "rocky",
        bankAngle: "medium",
        clarity: "average",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/13/c0/b7/87/fun-at-the-lake.jpg?w=1400&h=-1&s=1",
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/32/ce/c7/caption.jpg?w=1200&h=-1&s=1",
        ],
      },
      {
        date: "2022-06-19T15:54:00+0000",
        location: {
          name: "River Lugg, Herefordshire",
          id: null,
        },
        notes:
          "Water was murky but lovely and warm. It's a lovely place to spend some time - we took a picnic and sat on the grassy banks all day.",
        stars: 4,
        recordTemp: 16,
        feelTemp: "warm",
        mins: 25,
        km: 0.4,
        outOfDepth: true,
        sizeKey: "small",
        shore: "grassy",
        bankAngle: "steep",
        clarity: "muddy",
        imgUrls: [
          "https://live.staticflickr.com/65535/52220565017_c45574f31a_b.jpg",
        ],
      },
      {
        date: "2023-05-19T12:47:00+0000",
        location: {
          name: "River Dart, Devon",
          id: null,
        },
        notes:
          "Great spot for a wee dip. Good if you don't like getting out of your depth as doesn't get too deep too.",
        stars: 5,
        recordTemp: 13,
        feelTemp: "average",
        mins: 20,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "small",
        shore: "rocky",
        bankAngle: "medium",
        clarity: "clear",
        imgUrls: [
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReIZWz2gy38q7hn331fnNTXM6LoIFAa4zfU0n2CyN6JFAyxoE675lwyuHkwIw0Okhdrdc&usqp=CAU",
          "https://static.wixstatic.com/media/a4c8d4_c79dd5fe4ddb439eab68988d88b11b8a~mv2.jpeg/v1/fill/w_640,h_402,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/a4c8d4_c79dd5fe4ddb439eab68988d88b11b8a~mv2.jpeg",
        ],
      },
      {
        date: "2022-07-20T08:27:00+0000",
        location: {
          name: "River Dart, Devon",
          id: null,
        },
        notes:
          "Still and clear waters made for a perfect early-morning swim. Not too deep either.",
        stars: 5,
        recordTemp: 14,
        feelTemp: "average",
        mins: 18,
        km: 0.2,
        outOfDepth: true,
        sizeKey: "small",
        shore: "rocky",
        bankAngle: "shallow",
        clarity: "perfect",
        imgUrls: [
          "https://thecornishlife.co.uk/wp-content/uploads/2020/10/river-dart-devon-6.jpg",
          "https://thecornishlife.co.uk/wp-content/uploads/2020/10/river-dart-devon-15-767x1024.jpg",
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_ATYNprRTRWLbseyUrsBNUYBKgNmNxAbX2BxmT71I5Fg3nSzKJDFoUGwSwXeR8-mqZXY&usqp=CAU",
        ],
      },
      {
        date: "2023-02-15T07:30:00+0000",
        location: {
          name: "Durdle Door, Dorset",
          id: null,
        },
        notes:
          "Quick morning dip with my friend Val. Wet and windy so not for the fainthearted, but exhilarating! Bring a flask for after!",
        stars: 5,
        recordTemp: null,
        feelTemp: "freezing",
        mins: 6,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "murky",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/1f/e4/d7/photo3jpg.jpg?w=1400&h=-1&s=1",
        ],
      },
      {
        date: "2023-04-15T10:47:00+0000",
        location: {
          name: "Watendlath Tarn, Keswick",
          id: null,
        },
        notes:
          "Really secluded place tucked out the way with a lovely little cafe right alongside. Some pond weed and lily pads when you get in, but further out it clears. Water was bloomin' freezing too! Will definitely come back once the weather gets a bit warmer though",
        stars: 4,
        recordTemp: 9,
        feelTemp: "freezing",
        mins: 7,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "grassy",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://swimmingthelakes.files.wordpress.com/2015/06/watendlath-tarn-buttermere-072.jpg",
          "https://swimmingthelakes.files.wordpress.com/2015/06/watendlath-tarn-buttermere-034.jpg",
        ],
      },
      {
        date: "2022-08-06T15:45:00+0000",
        location: {
          name: "Derwentwater, Lake District",
          id: null,
        },
        notes:
          "Busy during the summer holidays. Be careful of canoes, kayaks and the ferry if you're swimming further out - there are some secluded spots towards Portinscale and Friars Crag that are better if you want a quieter swim",
        stars: 3,
        recordTemp: 14,
        feelTemp: "average",
        mins: 30,
        km: 0.5,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/ea/4f/41/caption.jpg?w=1400&h=-1&s=1",
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/19/b3/91/71/low-level-views-across.jpg?w=1400&h=-1&s=1",
        ],
      },
      {
        date: "2023-05-16T16:05:00+0000",
        location: {
          name: "Crummock Water, Lake District",
          id: null,
        },
        notes:
          "Nice place for an afternoon dip amidst the fells. Water was pretty cold so wetsuit was in order. Clean waters and easy to access",
        stars: 4,
        recordTemp: 11,
        feelTemp: "cold",
        mins: 15,
        km: 0.3,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://3.bp.blogspot.com/-dOQuXS206YI/UFeCNEnQKgI/AAAAAAAAH1s/mOexGqV-R_A/s1600/000_0006.JPG",
          "http://4.bp.blogspot.com/-3YiGI1ily7o/UFeBU84s_XI/AAAAAAAAH1k/myKPN85GdOw/s640/000_0005.JPG",
        ],
      },
      {
        date: "2022-08-11T13:00:00+0000",
        location: {
          name: "Grasmere Lake, Lake District",
          id: null,
        },
        notes:
          "Always a favourite! This time we swam out to the little island from the west side of the lake - only around 200m, but wouldn't recommend this unless you're a pretty confident swimmer.",
        stars: 5,
        recordTemp: 17,
        feelTemp: "warm",
        mins: 25,
        km: 0.7,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://anywhereweroam.com/wp-content/uploads/2023/04/grasmere-lake-district-swim-2.jpg",
          "https://anywhereweroam.com/wp-content/uploads/2023/04/grasmere-lake-district-swim-1.jpg",
        ],
      },
      {
        date: "2023-03-21T10:30:00+0000",
        location: {
          name: "Wast Water, Lake District",
          id: null,
        },
        notes:
          "Bracing swim this March morning. Sun was shining but the water was super chilly.",
        stars: 4,
        recordTemp: 9,
        feelTemp: "freezing",
        mins: 5,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://westernlakedistrict.com/wp-content/uploads/Crummock-Water-1024x640.jpg",
          "https://media.istockphoto.com/id/1056309552/photo/beautiful-landscape-view-of-wast-water-in-the-lake-district-national-park-in-the-uk-a-girl.jpg?s=612x612&w=0&k=20&c=gx9plOMK6FNHRHrYXXfcQ86SGzyCh_l037Ixwf6J6KU=",
          "https://eu-assets.simpleview-europe.com/golakes/imageresizer/?image=%2Fdmsimgs%2Fwastwater_2105828655.jpg&action=ProductDetailProFullWidth",
        ],
      },
      {
        date: "2023-06-23T12:00:00+0000",
        location: {
          name: "Black Moss Pot, Keswick",
          id: null,
        },
        notes:
          "Beautiful swimming hole! Will be coming back. Water is pretty nippy even in warmer weather, but a refreshing dip in beautiful clear water.",
        stars: 5,
        recordTemp: 12,
        feelTemp: "freezing",
        mins: 5,
        km: null,
        outOfDepth: true,
        sizeKey: "tiny",
        shore: "rocky",
        bankAngle: "jump-in",
        clarity: "perfect",
        imgUrls: [
          "https://anywhereweroam.com/wp-content/uploads/2022/02/black-moss-pot-lake-district-14.jpg",
          "https://anywhereweroam.com/wp-content/uploads/2022/02/black-moss-pot-lake-district-19.jpg",
          "https://anywhereweroam.com/wp-content/uploads/2022/02/black-moss-pot-lake-district-12.jpg",
        ],
      },
      {
        date: "2023-07-07T16:40:00+0000",
        location: {
          name: "Coniston Water, Cumbria",
          id: null,
        },
        notes:
          "The water wasn't the clearest but the weather hasn't been great recently so understandable. Nice enough swim but not my favourite spot.",
        stars: 3,
        recordTemp: 15,
        feelTemp: "average",
        mins: 40,
        km: 1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/2d/90/49/caption.jpg?w=1100&h=-1&s=1",
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/2d/8b/9f/caption.jpg?w=1400&h=-1&s=1",
        ],
      },
      {
        date: "2023-09-02T11:00:00+0000",
        location: {
          name: "Buttermere Pools, Lake District",
          id: null,
        },
        notes:
          "Gorgeous pool by a quaint waterfall - feels like you're in an infinity pool!",
        stars: 5,
        recordTemp: 11,
        feelTemp: "cold",
        mins: 15,
        km: null,
        outOfDepth: false,
        sizeKey: "tiny",
        shore: "rocky",
        bankAngle: "medium",
        clarity: "perfect",
        imgUrls: [
          "https://images.squarespace-cdn.com/content/v1/596b2969d2b85786e6892853/9255da1f-7dfa-442e-acbc-1420cafd0bf0/Buttermere+infinity+pool+from+above?format=1500w",
          "https://images.squarespace-cdn.com/content/v1/596b2969d2b85786e6892853/7d109197-ed8e-4783-9174-069264f4529b/The+buttermere+infinity+pool%2C+Lake+District?format=1500w",
          "https://images.squarespace-cdn.com/content/v1/596b2969d2b85786e6892853/df4dc503-e9c4-4d2b-a4e7-5fdb4b86860b/The+views+from+the+Buttermere+Infinity+pool?format=1500w",
          "https://images.squarespace-cdn.com/content/v1/596b2969d2b85786e6892853/e142536d-5ac8-401c-b110-4cd326b1b1a2/Walking+up+to+the+next+pools?format=1500w",
        ],
      },
    ],
  },
  {
    uid: "evHxmWh0Y9UpaKMxJPlb9LMW9il2",
    name: "Aiman, Vladimir Campbell",
    nickname: "Aymannotcool",
    profileImg:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cmFuZG9tJTIwcGVvcGxlfGVufDB8fDB8fHww&w=1000&q=80",
    dob: "1999-01-15T22:00:00+0000",
    home: "Shrewsbury, UK",
    bio: "I can swim 2km in under 30 minutes. I am like lightening in the water.",
    swims: [
      {
        date: "2023-03-31T08:00:00+0000",
        location: {
          name: "Sandsend Beach, Whitby",
          id: null,
        },
        notes:
          "Has become my daily swim spot since moving nearby. Really beautiful morning today!",
        stars: 5,
        recordTemp: 10,
        feelTemp: "cold",
        mins: 10,
        km: 0.5,
        outOfDepth: true,
        sizeKey: "large",
        shore: "sandy",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/bd/a8/4e/sandsend-beach.jpg?w=1400&h=-1&s=1",
        ],
      },
      {
        date: "2023-04-05T16:30:00+0000",
        location: {
          name: "National Trust - Fell Foot, Windermere",
          id: null,
        },
        notes:
          "Water seemed a bit murkier than usual but a good swim regardless.",
        stars: 4,
        recordTemp: 10,
        feelTemp: "average",
        mins: 30,
        km: 1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "medium",
        clarity: "murky",
        imgUrls: [
          "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/12/82/87/0e/20180401-135947-largejpg.jpg?w=800&h=-1&s=1",
        ],
      },
      {
        date: "2023-05-19T14:00:00+0000",
        location: {
          name: "Rydal, Lake District",
          id: null,
        },
        notes:
          "Gorgeous swim at Rydal Water today! Water was a little bit cold so had to put my swim gloves and hat on",
        stars: 5,
        recordTemp: 12,
        feelTemp: "cold",
        mins: 10,
        km: null,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "perfect",
        imgUrls: [
          "https://swimmingthelakes.files.wordpress.com/2015/10/rydal-water-035.jpg",
        ],
      },
      {
        date: "2022-11-29T10:50:00+0000",
        location: {
          name: "Ullswater, Lake District",
          id: null,
        },
        notes:
          "Water was freezing so wear your thick wetsuit! Nice swim with clean water.",
        stars: 4,
        recordTemp: 10,
        feelTemp: "cold",
        mins: 30,
        km: 0.75,
        outOfDepth: true,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://another.place/wp-content/uploads/2019/03/Swimming-in-Ullswater.jpg",
        ],
      },
      {
        date: "2022-05-27T17:30:00+0000",
        location: {
          name: "Loweswater, Cumbria",
          id: null,
        },
        notes:
          "Lovely evening swim at Loweswater with blue skies and warm water. Met some fellow wild swimmers there who advised not to go in peak summer months because of the algae risk, but seemed fine when we went",
        stars: 4,
        recordTemp: 15,
        feelTemp: "warm",
        mins: 20,
        km: 0.45,
        outOfDepth: true,
        sizeKey: "large",
        shore: "grassy",
        bankAngle: "shallow",
        clarity: "clear",
        imgUrls: [
          "https://swimmingthelakes.files.wordpress.com/2016/08/dscf7599.jpg?w=1024&h=768",
          "https://swimmingthelakes.files.wordpress.com/2016/08/dscf7608.jpg?w=1024&h=768",
          "https://swimmingthelakes.files.wordpress.com/2016/08/dscf7638.jpg?w=1024&h=768",
          "https://swimmingthelakes.files.wordpress.com/2016/08/dscf7611.jpg?w=1024&h=768",
        ],
      },
      {
        date: "2023-05-06T13:00:00+0000",
        location: {
          name: "Bassenthwaite Lake, Cumbria",
          id: null,
        },
        notes:
          "Nice spot down by St Begas Church. Easy access in and out of the water, and it gradually gets deeper so no sudden surprises. Water was a little silty but a great swim nonetheless.",
        stars: 4,
        recordTemp: 14,
        feelTemp: "average",
        mins: 15,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "large",
        shore: "pebbly",
        bankAngle: "shallow",
        clarity: "average",
        imgUrls: [
          "https://eu-assets.simpleview-europe.com/golakes/imageresizer/?image=%2Fdmsimgs%2F4591C12B070DB732A900F686FDCBA8531A838395.jpg&action=ProductDetailProFullWidth",
          "https://img.keswick.org/cdn-cgi/image/w=2724,q=80,f=auto/original/50709.jpg",
        ],
      },
      {
        date: "2022-06-16T14:20:00+0000",
        location: {
          name: "Styhead Tarn, Borrowdale",
          id: null,
        },
        notes:
          "Cute little tarn - water is colder than it looks! Thankfully left enough tea in the flask for a post-swim cuppa. Stunning area and a nice hike up to the tarn, a solid 4/5 stars (water gets deep really quickly so knocked a star off).",
        stars: 4,
        recordTemp: 12,
        feelTemp: "cold",
        mins: 10,
        km: 0.1,
        outOfDepth: true,
        sizeKey: "small",
        shore: "swampy",
        bankAngle: "steep",
        clarity: "murky",
        imgUrls: [
          "https://runningin3time.files.wordpress.com/2021/05/sty-head-and-sprinkling-tarns-by-penny-1.jpg",
          "https://runningin3time.files.wordpress.com/2021/05/sty-head-and-sprinkling-tarns-may-2021-12.jpg",
        ],
      },
      {
        date: "2023-08-08T11:18:00+0000",
        location: {
          name: "Grantchester Meadows, Cambridge",
          id: null,
        },
        notes:
          "Water felt really warm and even though it's a river it isn't fast flowing so feels safe enough, but the water was really filthy. Not too keen on the cows being so close by either.",
        stars: 3,
        recordTemp: 17,
        feelTemp: "warm",
        mins: 20,
        km: 0.3,
        outOfDepth: true,
        sizeKey: "medium",
        shore: "grassy",
        bankAngle: "steep",
        clarity: "muddy",
        imgUrls: [
          "https://www.klpa.uk/wp-content/uploads/2021/07/bWPDDsUIkUAayYp-800x450-noPad.jpg",
          "https://waterlogreswum.files.wordpress.com/2012/08/granta.jpg",
        ],
      },
    ],
  },
];
